import { Inter, Lora } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const loraCyrillic = Lora({
  subsets: ['cyrillic'],
  style: ['italic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-lora-cyrillic',
  display: 'swap',
  adjustFontFallback: false,
});
const loraRegular = Lora({
  subsets: ['latin'],
  variable: '--font-lora-regular',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  adjustFontFallback: false,
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${loraCyrillic.variable} ${loraRegular.variable} bg-yellowishGray font-lora-regular flex flex-col min-h-svh `}
      >
        <Navigation />
        <div>{children}</div>

        <Footer />
      </body>
    </html>
  );
}
